version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ['*']

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    groups:
      python-direct-dependencies:
        patterns: ['*']

  - package-ecosystem: npm
    directory: /client
    schedule:
      interval: weekly
    groups:
      client-dependencies:
        patterns: ['*']

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
